### PR TITLE
[JENKINS-59406] Test on 2.190.1

### PR DESCRIPTION
**Pull request by batmat**
DO NOT MERGE.

Testing the impact of https://issues.jenkins-ci.org/browse/JENKINS-59406

### CODE REVIEW

**Comment by batmat** [comment]
Failing as expected: 
image

image

**Comment by timja** [comment]
> Failing as expected:
> image
> 
> image

@batmat any details on why it's expected to fail? this is one of the plugins blocking the bom 2.190.x line currently
https://github.com/jenkinsci/bom/pull/110#issuecomment-579625625

**Comment by timja** [comment]
Ah I see the ticket will take a look

**Comment by timja** [comment]
I think this can be closed, the fix was back-ported to 2.190.2

**Comment by oleg-nenashev** [comment]
@batmat ^

**Pull request closed without merging**
