### PR TITLE
Credentials dependency fix

### PR DESCRIPTION
**Pull request by jglick**
Without this you get a long ugly stack trace during startup if `credentials` is disabled. With the fix you get just

```
… hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1 error
WARNING: Failed to instantiate optional component com.cloudbees.hudson.plugins.folder.properties.FolderCredentialsProvider$FolderCredentialsProperty$DescriptorImpl; skipping
```

@reviewbybees esp. @daniel-beck

### CODE REVIEW

**Comment by jglick** [comment]
CI build seems to be getting OOMEs. Will try switching to Java 8.

**Comment by jglick** [comment]
There we go @daniel-beck.

**Comment by oleg-nenashev** [comment]
LGTM :bee:

**Comment by recena** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Pull request merged**
