### PR TITLE
[FIXED JENKINS-47077] Prevent sympathetic harmonization so that interval actually works

### PR DESCRIPTION
**Pull request by stephenc**
@reviewbybees

### CODE REVIEW

**Comment by stephenc** [comment]
This should only affect the time difference compared not the crontab

**Comment by jglick** [comment]
So you are modifying the return value of `toIntervalMillis`. That will definitely affect the value of `PeriodicFolderTrigger.interval`. It _could_ also affect the return value of `toCrontab` and thus the value of `Trigger.spec`. Unclear from reading whether the changed value would cause one of the threshold calculations to switch to a new value. You are only subtracting 1s and the comparisons start at 5m, yet `doFillIntervalItems` specifically offers exactly 5m as an option (for example), meaning

```java
if (millis < TimeUnit2.MINUTES.toMillis(5)) {
```

could switch from `false` (an exact match) to `true` (off by 1000ms). Thus changing the crontab for the `5m` option from `* * * * *` (every minute) to `H/12 * * * *` (every 5m) IIUC. Intentional?

Saved settings would be affected if you opened and resaved the configuration form.

**Comment by jglick** [comment]
BTW please merge with `master` to recheck the PR build.

**Comment by stephenc** [comment]
A test would need to run for at least 4 minutes to prove the functionality works... not the kind of test I'd like to add here.

**Comment by jglick** [comment]
Understood that testing this would be tricky without some kind of mock clock. Anyway, was

> changing the crontab for the `5m` option from `* * * * *` (every minute) to `H/12 * * * *` (every 5m)

intentional, an accident, or not actually true at all…?

**Comment by jglick** [comment]
ping @stephenc

**Comment by jglick** [comment]
Related to [JENKINS-47077](https://issues.jenkins-ci.org/browse/JENKINS-47077)?

**Comment by stephenc** [comment]
@jglick well ` TimeUnit2.MINUTES.toMillis(5) <  TimeUnit2.MINUTES.toMillis(5) == false` so ` TimeUnit2.MINUTES.toMillis(5) - 1000L <  TimeUnit2.MINUTES.toMillis(5) == false` is not changing anything much there...

**Comment by stephenc** [comment]
@jglick actually I moved the change to only do the delta in the comparison. No change to persistence at all

**Comment by stephenc** [comment]
superseded by #119

**Pull request closed without merging**
