### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by darxriggs**
The deprecated classes/methods have been found by https://ci.jenkins.io/job/Infra/job/deprecated-usage-in-plugins/job/master/lastSuccessfulBuild/artifact/output/usage-by-plugin.html.

I suggest to review the changes commit by commit.

### CODE REVIEW

**Comment by darxriggs** [comment]
Hi @fcojfernandez and @oleg-nenashev, as some time already passed since this pull-request was created, I just wanted to check if it can be merged?

**Comment by oleg-nenashev** [comment]
I am not sure who maintains this plugin nowadays

**Comment by oleg-nenashev** [comment]
Will check

**Comment by darxriggs** [comment]
I added another commit to replace `View#getOwnerItemGroup`.

**Comment by darxriggs** [comment]
Hi @fcojfernandez, I now rebased on master and resolved the merge conflict.

**Comment by fcojfernandez** [comment]
@darxriggs I think I will be able to work in this next week. Thanks a lot!

**Pull request merged**
