### PR TITLE
[JENKINS-32179] Logic error when computeChildren suggested the same child name twice during recomputation

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-32179](https://issues.jenkins-ci.org/browse/JENKINS-32179)

Supersedes https://github.com/jenkinsci/branch-api-plugin/pull/23.

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
The failure seems to be in Javadoc. Have not managed to reproduce locally.

**Comment by jglick** [comment]
I even downloaded JDK 8u60 but could not reproduce the error:

```
/scratch/jenkins/workspace/plugins/cloudbees-folder-plugin/src/main/java/com/cloudbees/hudson/plugins/folder/relocate/DefaultRelocationUI.java:99: warning: no @param for item
    public HttpResponse doMove(StaplerRequest req, @AncestorInPath Item item, @QueryParameter String destination) throws
                        ^
/scratch/jenkins/workspace/plugins/cloudbees-folder-plugin/src/main/java/com/cloudbees/hudson/plugins/folder/relocate/DefaultRelocationUI.java:99: warning: no @throws for java.io.IOException
    public HttpResponse doMove(StaplerRequest req, @AncestorInPath Item item, @QueryParameter String destination) throws
                        ^
/scratch/jenkins/workspace/plugins/cloudbees-folder-plugin/src/main/java/com/cloudbees/hudson/plugins/folder/relocate/DefaultRelocationUI.java:99: warning: no @throws for java.lang.InterruptedException
    public HttpResponse doMove(StaplerRequest req, @AncestorInPath Item item, @QueryParameter String destination) throws
                        ^
javadoc: error - com.sun.tools.doclets.internal.toolkit.util.DocletAbortException: java.lang.ClassCastException: com.sun.tools.javadoc.MethodDocImpl cannot be cast to com.sun.tools.javadoc.AnnotationTypeElementDocImpl
```

**Comment by jglick** [comment]
[HSTTWO-3262](https://issues.onehippo.com/browse/HSTTWO-3262) seems to report something similar.

BTW it is not limited to this PR—the CI build has been hitting this intermittently.

**Comment by jglick** [comment]
Must be either at [`DocEnv.java:702`](http://hg.openjdk.java.net/jdk8u/jdk8u/langtools/file/e8e293d0db49/src/share/classes/com/sun/tools/javadoc/DocEnv.java#l702) or line 720; those are the only such casts.

**Comment by jglick** [comment]
Note: there was an apparently transient Javadoc error, tracked in #43 but not diagnosed, so I just [turned off Javadoc generation](https://jenkins.ci.cloudbees.com/job/plugins/job/cloudbees-folder-plugin/configure) on this plugin.

**Comment by kzantow** [comment]
:bee:

**Pull request merged**
