### PR TITLE
Fix to use the icon element in folder title

### PR DESCRIPTION
**Pull request by bitwiseman**
See [JENKINS-66148](https://issues.jenkins-ci.org/browse/JENKINS-66148).

Related to https://github.com/jenkinsci/github-branch-source-plugin/pull/443

### Proposed changelog entries

* Entry 1: Issue, Human-readable Text
* ...

### Submitter checklist

- [ ] JIRA issue is well described
- [ ] Changelog entry appropriate for the audience affected by the change (users or developer, depending on the change).
      * Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
- [ ] Appropriate autotests or explanation to why this change has no tests

### CODE REVIEW

**Review by alecharp — APPROVED** [review]
looks good to me

**Comment by timja** [comment]
I deployed this to ci.jenkins.io, I just see an empty space?

image

https://ci.jenkins.io/job/Core/job/acceptance-test-harness/

**Comment by bitwiseman** [comment]
@timja it also needs https://github.com/jenkinsci/github-branch-source-plugin/pull/443 to work.

**Comment by timja** [comment]
ah my bad works now

**Pull request merged**
